import type { Metadata } from "next";
import "@/app/globals.css";
import { Toaster } from "@/components/ui/sonner";
import { Suwannaphum } from "next/font/google";

const suwannaphum = Suwannaphum({
  weight: ["100", "300", "400", "700", "900"],
  variable: "--font-suwannaphum",
  display: "swap",
  subsets: ["khmer"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
      <body className={`${suwannaphum.className} bg-background_color`}>
      <main className="w-full">
        {children}
        <Toaster closeButton />
      </main>
      </body>
      </html>
  );
}