import { ArrowLeft } from "lucide-react";
import Link from "next/link";

export default function page() {
    
    return (
        <section className="mx-5">
            <div className="flex gap-10 py-8 items-center">
                <Link href={`/`}><ArrowLeft  className="w-8 h-8" /></Link>
                <h1 className="text-2xl">Privacy Policy</h1>
            </div>
            <p className="text-black/60 text-lg">O2 Free Classifieds strives to offer its visitors the many advantages of web technology and to provide an Agri-products&#44; technical support and business/enterprise development consultant. We may use Personally Identifiable Information &#40;your name&#44; e-mail address&#44; address&#44; telephone number&#41; subject to the terms of this privacy policy. We will never provide&#44; barter&#44; or rent your email address to any unauthorized third party.</p>
            <p className="text-black/60 text-lg py-6">We recognize the importance of protecting your privacy and our policy is designed to assist you in understanding how we collect data&#44; use and safeguard the personal information you provide to us and to assist you in making informed decisions when using our site. This policy will be continuously assessed against new technologies&#44; business practices and our customer&apos;s needs.</p>
            <h2 className="text-2xl py-6">What Information Do We Collect?</h2>
            <p className="text-black/60 text-lg">When you visit this web site you may provide us with two types of information: personal information you knowingly choose to disclose that is collected on an individual basis and Web site use information collected on a form basis as you and others browse our Web site.</p>
            <h2 className="text-2xl py-6">1. Personal Information You Choose to Provide</h2>
            <p className="text-black/60 text-lg">Registration Information: When you register for use of our website services you will provide us information about yourself such as Name&#44; gender&#44; Email&#44; phone number and Country</p>
            <p className="text-black/60 text-lg py-6">Personal Profile Information: Other Personally Identifiable Information that you voluntarily disclose in your Personal Profile page that is not required during registration.</p>
            <p className="text-black/60 text-lg py-6">Register using your Google account: We collect first name&#44; last name&#44; gender&#44; profile picture and email address</p>
            <h2 className="py-6 text-2xl ">2. Web Site Use Information</h2>
            <p className="text-black/60 text-lg">Similar to other commercial Web sites&#44; our Web site utilizes a standard technology called &quot;cookies&quot; &#40;see explanation below&#44; &rdquo;What Are Cookies?&rdquo;&#41; and web server log files to collect information about how our Web site is used. Information gathered through cookies and Web server logs may include the date and time of visits&#44; the pages viewed&#44; time spent at our Web site&#44; and the Web sites visited just before and just after our Web site.</p>
            <h2 className="text-2xl py-6">What Are Cookies?</h2>
            <p className="text-lg text-black/60">A cookie is a very small text document&#44; which often includes an anonymous unique identifier. When you visit a Web site&#44; that site&apos;s computer asks your computer for permission to store this file in a part of your hard drive specifically designated for cookies. Each Web site can send its own cookie to your browser if your browser&apos;s preferences allow it&#44; but &#40;to protect your privacy&#41; your browser only permits a Web site to access the cookies it has already sent to you&#44; not the cookies sent to you by other sites. Browsers are usually set to accept cookies. However&#44; if you would prefer not to receive cookies&#44; you may alter the configuration of your browser to refuse cookies. If you choose to have your browser refuse cookies&#44; it is possible that some areas of our site will not function as effectively when viewed by the users. A cookie cannot retrieve any other data from your hard drive or pass on computer viruses.</p>
            <h2 className="text-2xl py-6">What we do with the information we collect</h2>
            <p className="text-black/60 text-lg">A cookie is a very small text document&#44; which often includes an anonymous unique identifier. When you visit a Web site&#44; that site&apos;s computer asks your computer for permission to store this file in a part of your hard drive specifically designated for cookies. Each Web site can send its own cookie to your browser if your browser&apos;s preferences allow it&#44; but &#40;to protect your privacy&#41; your browser only permits a Web site to access the cookies it has already sent to you&#44; not the cookies sent to you by other sites. Browsers are usually set to accept cookies. However&#44; if you would prefer not to receive cookies&#44; you may alter the configuration of your browser to refuse cookies. If you choose to have your browser refuse cookies&#44; it is possible that some areas of our site will not function as effectively when viewed by the users. A cookie cannot retrieve any other data from your hard drive or pass on computer viruses.</p>
            <p className="text-black/60 text-lg py-6">Occasionally&#44; we may also use the information we collect to notify you about important changes to our website&#44; new services&#44; and special offers we think you will find valuable. You may notify us at any time if you do not wish to receive these offers by emailing us at the link provided on the newsletter.</p>
            <p className="text-black/60 text-lg py-6">Aggregated Information &#40;information that does not personally identify you&#41; may be used in many ways. For example&#44; we may combine information about your usage patterns with similar information obtained from other users to help enhance our site and services &#40;e.g.&#44; to learn which pages are visited most or what features are most attractive&#41;. Aggregated Information may occasionally be shared with our advertisers and business partners. Again&#44; this information does not include any Personally Identifiable Information about you or allow anyone to identify you individually.</p>
            <p className="text-black/60 text-lg py-6">We will use your information only as permitted by-law. In addition&#44; from time to time as we continue to develop our business&#44; we may provide&#44; buy&#44; merge or partner with other companies or businesses. In such transactions&#44; user information may be among the transferred assets. We may also disclose your information in response to a court order&#44; at other times when we believe we are reasonably required to do so by-law&#44; in connection with the collection of amounts you may owe to us&#44; and/or to law enforcement authorities whenever we deem it appropriate or necessary. Please note we may not provide you with notice prior to disclosure in such cases.</p>
            <p className="text-black/60 text-lg py-6">If you log in using your mobile number or email id&#44; we use your first name and last name&#44; mobile number and/or e-mail address to identify you as a user and provide access to our Platform.</p>
            <p className="text-black/60 text-lg py-6">We will use your information only as permitted by-law. In addition&#44; from time to time as we continue to develop our business&#44; we may provide&#44; buy&#44; merge or partner with other companies or businesses. In such transactions&#44; user information may be among the transferred assets. We may also disclose your information in response to a court order&#44; at other times when we believe we are reasonably required to do so by-law&#44; in connection with the collection of amounts you may owe to us&#44; and/or to law enforcement authorities whenever we deem it appropriate or necessary. Please note we may not provide you with notice prior to disclosure in such cases.</p>
            <p className="text-black/60 text-lg py-6">Affiliated sites&#44; linked sites and advertisements</p>
            <p className="text-black/60 text-lg py-6">O2 Classifieds expects its partners&#44; advertisers and affiliates to respect the privacy of our users. Be aware&#44; however&#44; that third parties&#44; including our partners&#44; advertisers&#44; affiliates and other content providers accessible through our site&#44; may have their own privacy and data collection policies and practices. O2 Free Classifieds is not responsible for the actions or policies of such third parties. You should check the applicable privacy policies of those third parties when providing information on a feature or page operated by a third party.</p>
            <p className="text-black/60 text-lg py-6">While on our site&#44; our advertisers&#44; promotional partners or other third parties may use cookies or other technology to attempt to identify some of your preferences or retrieve information about you. For example&#44; some of our advertising is served by third parties and may include cookies that enable the advertiser to determine whether you have seen a particular advertisement before. Other features available on our site may offer services operated by third parties and may use cookies or other technology to gather information. O2 Free Classifieds does not control the use of this technology by third parties or the resulting information&#44; and is not responsible for any actions or policies of such third parties.</p>
            <p className="text-black/60 text-lg py-6">You should also be aware that if you voluntarily disclose Personally Identifiable Information on chat boards or in Personal Profile page&#44; that information can be viewed publicly and can be collected and used by third parties without our knowledge and may result in unsolicited messages from other individuals or third parties. Such activities are beyond the control of O2 Free Classifieds and this policy.</p>
            <h2 className="text-2xl py-6">What About Other Web Sites Linked to Our Web Site?</h2>
            <p className="text-black/60 text-lg py-6">We are not responsible for the practices employed by Web sites linked to or from our Web site or the information or content contained therein. Often links to other Web sites are provided solely as pointers to information on topics that may be useful to the users of our Web site.</p>
            <p className="text-black/60 text-lg py-6">Please remember that when you use a link to go from our website to another web site&#44; our Privacy Policy is no longer in effect. Your browsing and interaction on any other web site&#44; including web sites&#44; which have a link on our Website&#44; is subject to that Web site&apos;s own rules and policies. Please read over those rules and policies before proceeding.</p>
            <h2 className="text-2xl py-6">Your Consent</h2>
            <p className="text-lg text-black/60">By using our Web site you consent to our collection and use of your personal information as described in this Privacy Policy. We reserve the right to amend this privacy policy at any time with or without notice.</p>
            <h2 className=" text-2xl py-6">Your rights - data deletion requests</h2>
            <p className="text-black/60 text-lg py-6">To exercise your privacy rights and choices&#44; if you do not want us to process your data&#44; then you can contact O2&apos;s customer service to request data deletion.</p>
            <h2 className="text-2xl py-6">Changes to this Policy</h2>
            <p className="text-lg text-black/60 py-6">O2 Free Classifieds reserves the rights to change this policy at any time. Please check this page periodically for changings. Your continued use of our site following the posting of changes to these terms will mean you accept those changes. Information collected prior to the time any change is posted will be used according to the rules and laws that applied at the time the information was collected.</p>
            <p className="py-6 text-center text-lg">Last Updated &#40; 2025 &#41; Copy Rights O2</p>
        </section>
    );
}
