// app/layout.tsx
import type { Metadata } from "next";
import "@/app/globals.css";
import { Suwannaphum } from "next/font/google";
import NavbarPage from "@/components/Navbar/NavbarPage";
import { Toaster } from "@/components/ui/sonner";
import { TooltipProvider } from '@radix-ui/react-tooltip'

const suwannaphum = Suwannaphum({
  weight: ["100", "300", "400", "700", "900"],
  variable: "--font-suwannaphum",
  display: "swap",
  subsets: ["khmer"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${suwannaphum.className} bg-background_color`}>
        <NavbarPage />
        <main className="w-full">
          <TooltipProvider>
             {children}
          </TooltipProvider>
          <Toaster closeButton />
        </main>
      </body>
    </html>
  );
}